// lib/models/task_model.dart
import 'package:hive/hive.dart';

part 'task_model.g.dart'; // Generated by build_runner

@HiveType(typeId: 0) // Ensure typeId is unique for each HiveObject
class TaskModel extends HiveObject {
  @HiveField(0)
  late String id; // Using cosObjectKey

  @HiveField(1)
  late String name;

  @HiveField(2)
  late String path; // Original local path

  @HiveField(3)
  late int size;

  @HiveField(4)
  late String formattedSize;

  @HiveField(5)
  late String type;

  @HiveField(6)
  late String uploadTime; // Timestamp of when it was added/uploaded

  @HiveField(7)
  late String sourceLanguage;

  @HiveField(8)
  late String targetLanguage;

  @HiveField(9)
  late String status; // e.g., "Uploaded", "Processing", "Completed"

  @HiveField(10)
  late String cosObjectKey;

  @HiveField(11)
  String? downloadUrl;

  @HiveField(12)
  String? errorMessage;

  TaskModel({
    required this.id,
    required this.name,
    required this.path,
    required this.size,
    required this.formattedSize,
    required this.type,
    required this.uploadTime,
    required this.sourceLanguage,
    required this.targetLanguage,
    required this.status,
    required this.cosObjectKey,
    this.downloadUrl,
    this.errorMessage,
  });
}